"""empty message

Revision ID: 4feed0684406
Revises: 
Create Date: 2022-11-05 12:03:09.862191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feed0684406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthroponym',
    sa.Column('anthroponym_id', sa.BIGINT(), nullable=False),
    sa.Column('anthroponym', sa.VARCHAR(length=512), nullable=True),
    sa.Column('original', sa.VARCHAR(length=512), nullable=False),
    sa.Column('transcription', sa.VARCHAR(length=512), nullable=False),
    sa.Column('source', sa.VARCHAR(length=512), nullable=False),
    sa.Column('comments', sa.VARCHAR(length=512), nullable=True),
    sa.Column('century', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('anthroponym_id'),
    sa.UniqueConstraint('anthroponym'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('source'),
    sa.UniqueConstraint('transcription')
    )
    op.create_table('literature',
    sa.Column('literature_id', sa.BIGINT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=512), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('published_at', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('literature_id'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('literature_id'),
    sa.UniqueConstraint('published_at'),
    sa.UniqueConstraint('title')
    )
    op.create_table('toponym',
    sa.Column('toponym_id', sa.BIGINT(), nullable=False),
    sa.Column('toponym', sa.VARCHAR(length=512), nullable=True),
    sa.Column('original', sa.VARCHAR(length=512), nullable=False),
    sa.Column('transcription', sa.VARCHAR(length=512), nullable=False),
    sa.Column('source', sa.VARCHAR(length=512), nullable=False),
    sa.Column('comments', sa.VARCHAR(length=512), nullable=True),
    sa.Column('century', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('toponym_id'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('source'),
    sa.UniqueConstraint('toponym'),
    sa.UniqueConstraint('transcription')
    )
    op.create_table('anthroponym_image',
    sa.Column('anthroponym_id', sa.BIGINT(), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['anthroponym_id'], ['anthroponym.anthroponym_id'], )
    )
    op.create_table('anthroponym_reference',
    sa.Column('literature_id', sa.BIGINT(), nullable=False),
    sa.Column('anthroponym_id', sa.BIGINT(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['anthroponym_id'], ['anthroponym.anthroponym_id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.literature_id'], )
    )
    op.create_table('toponym_image',
    sa.Column('toponym_id', sa.BIGINT(), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['toponym_id'], ['toponym.toponym_id'], )
    )
    op.create_table('toponym_reference',
    sa.Column('literature_id', sa.BIGINT(), nullable=False),
    sa.Column('toponym_id', sa.BIGINT(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.literature_id'], ),
    sa.ForeignKeyConstraint(['toponym_id'], ['toponym.toponym_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toponym_reference')
    op.drop_table('toponym_image')
    op.drop_table('anthroponym_reference')
    op.drop_table('anthroponym_image')
    op.drop_table('toponym')
    op.drop_table('literature')
    op.drop_table('anthroponym')
    # ### end Alembic commands ###
