"""empty message

Revision ID: 61f1ca62e01c
Revises: 6d56c9d18f72
Create Date: 2022-11-23 15:59:20.349200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f1ca62e01c'
down_revision = '6d56c9d18f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('geopos', table_name='toponym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('geopos', 'toponym', ['geopos'], unique=False)
    # ### end Alembic commands ###
