"""empty message

Revision ID: 6d56c9d18f72
Revises: c091220db900
Create Date: 2022-11-23 15:39:13.861375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d56c9d18f72'
down_revision = 'c091220db900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anthroponym_image', 'img',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('toponym', sa.Column('geopos', sa.VARCHAR(length=32), nullable=False))
    op.create_unique_constraint(None, 'toponym', ['geopos'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toponym', type_='unique')
    op.drop_column('toponym', 'geopos')
    op.alter_column('anthroponym_image', 'img',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
