"""empty message

Revision ID: 863a14dfaba8
Revises: 61f1ca62e01c
Create Date: 2022-11-27 02:30:18.055200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '863a14dfaba8'
down_revision = '61f1ca62e01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anthroponym', sa.Column('historical_source', sa.VARCHAR(length=512), nullable=True))
    op.add_column('anthroponym', sa.Column('ageographical_source', sa.VARCHAR(length=512), nullable=True))
    op.drop_index('source', table_name='anthroponym')
    op.drop_column('anthroponym', 'source')
    op.add_column('toponym', sa.Column('historical_source', sa.VARCHAR(length=512), nullable=True))
    op.add_column('toponym', sa.Column('ageographical_source', sa.VARCHAR(length=512), nullable=True))
    op.drop_index('source', table_name='toponym')
    op.drop_column('toponym', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toponym', sa.Column('source', mysql.VARCHAR(length=512), nullable=False))
    op.create_index('source', 'toponym', ['source'], unique=False)
    op.drop_column('toponym', 'ageographical_source')
    op.drop_column('toponym', 'historical_source')
    op.add_column('anthroponym', sa.Column('source', mysql.VARCHAR(length=512), nullable=False))
    op.create_index('source', 'anthroponym', ['source'], unique=False)
    op.drop_column('anthroponym', 'ageographical_source')
    op.drop_column('anthroponym', 'historical_source')
    # ### end Alembic commands ###
